;;; YS-Tools DCL toolbar controller
;;; Encoding: GBK/ANSI, CRLF

(setq *YS-Tools-DCL-Path*
  (if (and (boundp '*YS-Tools-Path*) *YS-Tools-Path*)
    (strcat *YS-Tools-Path* "\\dcl\\toolbar.dcl")
    nil
  )
)

(defun ys:run-command (cmd)
  (done_dialog 1)
  (vl-cmdf (strcat "_." cmd))
)

(defun ys:handle-button (key)
  (cond
    ((= key "btn_cont")   (ys:run-command "CONT"))
    ((= key "btn_txt")    (ys:run-command "TXT"))
    ((= key "btn_ysdl")   (ys:run-command "YSDL"))
    ((= key "btn_hei")    (ys:run-command "HEI"))
    ((= key "btn_qstxt")  (ys:run-command "QSTXT"))
    ((= key "btn_he")     (ys:run-command "HE"))
    ((= key "btn_qw")     (ys:run-command "QW"))
    ((= key "btn_wi")     (ys:run-command "WI"))
    ((= key "btn_gtx")    (ys:run-command "GTX"))
    ((= key "btn_gty")    (ys:run-command "GTY"))
    ((= key "btn_zhong")  (ys:run-command "ZHONG"))
    ((= key "btn_zuo")    (ys:run-command "ZUO"))
    ((= key "btn_you")    (ys:run-command "YOU"))
    ((= key "btn_shang")  (ys:run-command "SHANG"))
    ((= key "btn_xia")    (ys:run-command "XIA"))
    ((= key "btn_y")      (ys:run-command "Y"))
    ((= key "btn_rr")     (ys:run-command "RR"))
    ((= key "btn_uu")     (ys:run-command "UU"))
    ((= key "btn_gg")     (ys:run-command "GG"))
    ((= key "btn_syi")    (ys:run-command "SYI"))
    ((= key "btn_xyi")    (ys:run-command "XYI"))
    ((= key "btn_zyy")    (ys:run-command "ZYI"))
    ((= key "btn_yyi")    (ys:run-command "YYI"))
    ((= key "btn_yan")    (ys:run-command "YAN"))
    ((= key "btn_syan")   (ys:run-command "SYAN"))
    ((= key "btn_xyan")   (ys:run-command "XYAN"))
    ((= key "btn_xSUO")   (ys:run-command "XSUO"))
    ((= key "btn_sSUO")   (ys:run-command "SSUO"))
    ((= key "btn_sj")     (ys:run-command "SJ"))
    ((= key "btn_xj")     (ys:run-command "XJ"))
    ((= key "btn_long")   (ys:run-command "LONG"))
    ((= key "btn_excel")  (ys:run-command "EXCEL"))
    ((= key "btn_nu")     (ys:run-command "NU"))
    ((= key "btn_kuang")  (ys:run-command "KUANG"))
    ((= key "btn_bian")   (ys:run-command "BIAN"))
    ((= key "btn_lan")    (ys:run-command "LAN"))
    ((= key "btn_xin")    (ys:run-command "XIN"))
    ((= key "btn_xy")     (ys:run-command "XY"))
    ((= key "btn_pai")    (ys:run-command "PAI"))
    ((= key "btn_zdml")   (ys:run-command "ZDML"))
    ((= key "btn_hao")    (ys:run-command "HAO"))
    ((= key "btn_diag")   (ys:run-command "DIAGFRAME"))
    ((= key "close_btn")  (done_dialog 0))
    (T nil)
  )
)

(defun ys:show-toolbar (/ dcl_id)
  (cond
    ((null *YS-Tools-DCL-Path*)
     (princ "\n[YS-Tools] DCL path is not set."))
    ((not (findfile *YS-Tools-DCL-Path*))
     (princ (strcat "\n[YS-Tools] DCL file not found: " *YS-Tools-DCL-Path*)))
    (T
     (setq dcl_id (load_dialog *YS-Tools-DCL-Path*))
     (if (< dcl_id 0)
       (princ "\n[YS-Tools] Failed to load DCL dialog.")
       (progn
         (if (new_dialog "ys_tools_toolbar" dcl_id)
           (progn
             (foreach k '("btn_cont" "btn_txt" "btn_ysdl" "btn_hei" "btn_qstxt" "btn_he" "btn_qw" "btn_wi" "btn_gtx" "btn_gty" "btn_zhong" "btn_zuo" "btn_you" "btn_shang" "btn_xia" "btn_y" "btn_rr" "btn_uu" "btn_gg" "btn_syi" "btn_xyi" "btn_zyy" "btn_yyi" "btn_yan" "btn_syan" "btn_xyan" "btn_xSUO" "btn_sSUO" "btn_sj" "btn_xj" "btn_long" "btn_excel" "btn_nu" "btn_kuang" "btn_bian" "btn_lan" "btn_xin" "btn_xy" "btn_pai" "btn_zdml" "btn_hao" "btn_diag" "close_btn")
               (action_tile k (strcat "(ys:handle-button \"" k "\")"))
             )
             (start_dialog)
           )
           (princ "\n[YS-Tools] Failed to create toolbar dialog.")
         )
         (unload_dialog dcl_id)
       )
     )
    )
  )
  (princ)
)

(defun C:YSTOOLS ()
  (vl-load-com)
  (ys:show-toolbar)
)

(princ "\n[YS-Tools] toolbar.lsp loaded.")
(princ)
