;;; ====================================================================
;;; YS-Tools - ?????????
;;; ????: Y(???) RR(???) UU(???) GG(???)
;;; ====================================================================

(vl-load-com)

(defun c:Y (/ *error* doc undo-open targetColor ss i ename)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setq targetColor *Y_TextColor*)
  (princ "\n???????????????: ")
  (setq ss (ssget))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ename (ssname ss i))
        (vla-put-Color (vlax-ename->vla-object ename) targetColor)
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ (strcat "\n?????§Ø???????????"))
    )
    (princ "\n???????¦Ê¦Æ???")
  )
  (princ)
)

(defun c:RR (/ *error* doc undo-open targetColor ss i ename)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setq targetColor *RR_TextColor*)
  (princ "\n????????????????: ")
  (setq ss (ssget))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ename (ssname ss i))
        (vla-put-Color (vlax-ename->vla-object ename) targetColor)
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ "\n?????§Ø??????????")
    )
    (princ "\n???????¦Ê¦Æ???")
  )
  (princ)
)

(defun c:UU (/ *error* doc undo-open targetColor ss i ename)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setq targetColor *UU_TextColor*)
  (princ "\n????????????????: ")
  (setq ss (ssget))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ename (ssname ss i))
        (vla-put-Color (vlax-ename->vla-object ename) targetColor)
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ "\n?????§Ø??????????")
    )
    (princ "\n???????¦Ê¦Æ???")
  )
  (princ)
)

(defun c:GG (/ *error* doc undo-open targetColor ss i ename)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setq targetColor *GG_TextColor*)
  (princ "\n????????????????: ")
  (setq ss (ssget))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ename (ssname ss i))
        (vla-put-Color (vlax-ename->vla-object ename) targetColor)
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ "\n?????§Ø??????????")
    )
    (princ "\n???????¦Ê¦Æ???")
  )
  (princ)
)

(princ "\n[YS-Tools] color-tools.lsp loaded.")
(princ)
