;;; ====================================================================
;;; YS-Tools - ??牝??????
;;; ????: YAN SYAN XYAN XSUO SSUO SJ XJ LONG
;;; ====================================================================

(vl-load-com)

(defun c:YAN (/ *error* doc group_num extend_dir ss ent_list sorted_list i ent p10 p11 p10y p11y multiplier delta new_y new_pt obj)
  (defun *error* (msg)
    (if (and msg (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*")))
      (princ (strcat "\n????: " msg))
    )
    (if (= (type doc) 'vla-object) (vla-EndUndoMark doc))
    (princ)
  )
  (vl-load-com)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object)))
  (initget 1 "2 4")
  (setq group_num (atoi (getkword "\n?????????????? [2/4]: ")))
  (initget 1 "Up Down")
  (setq extend_dir (getkword "\n??????????? [????(Up)/????(Down)]: "))
  (princ "\n????????? (???????X????????): ")
  (setq ss (ssget '((0 . "LINE"))))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq ent_list '())
      (setq i 0)
      (repeat (sslength ss)
        (setq ent_list (cons (ssname ss i) ent_list))
        (setq i (1+ i))
      )
      (setq sorted_list
        (vl-sort ent_list
          '(lambda (e1 e2)
             (< (car (cdr (assoc 10 (entget e1))))
                (car (cdr (assoc 10 (entget e2)))))
           )
        )
      )
      (setq i 0)
      (foreach ent sorted_list
        (setq obj (entget ent))
        (setq p10 (cdr (assoc 10 obj)))
        (setq p11 (cdr (assoc 11 obj)))
        (setq multiplier (1+ (fix (/ i group_num))))
        (setq delta (* multiplier 5))
        (setq p10y (cadr p10))
        (setq p11y (cadr p11))
        (if (eq extend_dir "Down")
          (if (< p10y p11y)
            (progn
              (setq new_y (- p10y delta))
              (setq new_pt (list (car p10) new_y (caddr p10)))
              (setq obj (subst (cons 10 new_pt) (assoc 10 obj) obj))
            )
            (progn
              (setq new_y (- p11y delta))
              (setq new_pt (list (car p11) new_y (caddr p11)))
              (setq obj (subst (cons 11 new_pt) (assoc 11 obj) obj))
            )
          )
          (if (> p10y p11y)
            (progn
              (setq new_y (+ p10y delta))
              (setq new_pt (list (car p10) new_y (caddr p10)))
              (setq obj (subst (cons 10 new_pt) (assoc 10 obj) obj))
            )
            (progn
              (setq new_y (+ p11y delta))
              (setq new_pt (list (car p11) new_y (caddr p11)))
              (setq obj (subst (cons 11 new_pt) (assoc 11 obj) obj))
            )
          )
        )
        (entmod obj)
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (princ (strcat "\n???! ?????? " (itoa (length sorted_list)) " ??????"))
    )
    (princ "\n???????百汎???")
  )
  (princ)
)

(defun c:SYAN (/ ss i ent p1 p2 high low ang new_high)
  (princ "\n??????????????????...")
  (if (setq ss (ssget '((0 . "LINE"))))
    (progn
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (entget (ssname ss i)))
        (setq p1 (cdr (assoc 10 ent)))
        (setq p2 (cdr (assoc 11 ent)))
        (if (> (cadr p1) (cadr p2))
          (setq high p1 low p2)
          (setq high p2 low p1)
        )
        (setq ang (angle low high))
        (setq new_high (polar high ang 5))
        (if (equal high p1)
          (setq ent (subst (cons 10 new_high) (assoc 10 ent) ent))
          (setq ent (subst (cons 11 new_high) (assoc 11 ent) ent))
        )
        (entmod ent)
        (setq i (1+ i))
      )
      (princ (strcat "\n????????????? " (itoa i) " ??????"))
    )
    (princ "\n???????百?????")
  )
  (princ)
)

(defun c:XYAN (/ ss i ent p1 p2 high low ang new_low)
  (princ "\n??????????????????...")
  (if (setq ss (ssget '((0 . "LINE"))))
    (progn
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (entget (ssname ss i)))
        (setq p1 (cdr (assoc 10 ent)))
        (setq p2 (cdr (assoc 11 ent)))
        (if (< (cadr p1) (cadr p2))
          (setq low p1 high p2)
          (setq low p2 high p1)
        )
        (setq ang (angle high low))
        (setq new_low (polar low ang 5))
        (if (equal low p1)
          (setq ent (subst (cons 10 new_low) (assoc 10 ent) ent))
          (setq ent (subst (cons 11 new_low) (assoc 11 ent) ent))
        )
        (entmod ent)
        (setq i (1+ i))
      )
      (princ (strcat "\n????????????? " (itoa i) " ??????"))
    )
    (princ "\n???????百?????")
  )
  (princ)
)

(defun c:XSUO ( / *error* doc undo-open ss i ent entdata p10 p11 low_pt high_pt dx dy dz len ux uy uz new_pt is_p10_low)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (princ "\n?????????????????...")
  (setq ss (ssget '((0 . "LINE"))))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i))
        (setq entdata (entget ent))
        (setq p10 (cdr (assoc 10 entdata)))
        (setq p11 (cdr (assoc 11 entdata)))
        (if (< (cadr p10) (cadr p11))
          (setq low_pt p10 high_pt p11 is_p10_low T)
          (setq low_pt p11 high_pt p10 is_p10_low nil)
        )
        (setq dx (- (car high_pt) (car low_pt))
              dy (- (cadr high_pt) (cadr low_pt))
              dz (- (caddr high_pt) (caddr low_pt))
              len (sqrt (+ (* dx dx) (* dy dy) (* dz dz))))
        (if (> len 5.01)
          (progn
            (setq ux (/ dx len) uy (/ dy len) uz (/ dz len))
            (setq new_pt (list (+ (car low_pt) (* 5.0 ux))
                               (+ (cadr low_pt) (* 5.0 uy))
                               (+ (caddr low_pt) (* 5.0 uz))))
            (if is_p10_low
              (setq entdata (subst (cons 10 new_pt) (assoc 10 entdata) entdata))
              (setq entdata (subst (cons 11 new_pt) (assoc 11 entdata) entdata))
            )
            (entmod entdata)
            (entupd ent)
          )
          (princ (strcat "\n?? " (itoa (1+ i)) " ????????????"))
        )
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ (strcat "\nXSUO ?????????? " (itoa (sslength ss)) " ??????"))
    )
    (princ "\n???????????????2???")
  )
  (princ)
)

(defun c:SSUO ( / *error* doc undo-open ss i ent entdata p10 p11 low_pt high_pt dx dy dz len ux uy uz new_pt is_p10_low)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-open nil)
  (defun *error* (msg)
    (if undo-open
      (vl-catch-all-apply 'vla-EndUndoMark (list doc))
    )
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (princ "\n??????????????????...")
  (setq ss (ssget '((0 . "LINE"))))
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-open T)
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i))
        (setq entdata (entget ent))
        (setq p10 (cdr (assoc 10 entdata)))
        (setq p11 (cdr (assoc 11 entdata)))
        (if (< (cadr p10) (cadr p11))
          (setq low_pt p10 high_pt p11 is_p10_low T)
          (setq low_pt p11 high_pt p10 is_p10_low nil)
        )
        (setq dx (- (car high_pt) (car low_pt))
              dy (- (cadr high_pt) (cadr low_pt))
              dz (- (caddr high_pt) (caddr low_pt))
              len (sqrt (+ (* dx dx) (* dy dy) (* dz dz))))
        (if (> len 5.01)
          (progn
            (setq ux (/ dx len) uy (/ dy len) uz (/ dz len))
            (setq new_pt (list (- (car high_pt) (* 5.0 ux))
                               (- (cadr high_pt) (* 5.0 uy))
                               (- (caddr high_pt) (* 5.0 uz))))
            (if is_p10_low
              (setq entdata (subst (cons 11 new_pt) (assoc 11 entdata) entdata))
              (setq entdata (subst (cons 10 new_pt) (assoc 10 entdata) entdata))
            )
            (entmod entdata)
            (entupd ent)
          )
          (princ (strcat "\n?? " (itoa (1+ i)) " ????????????"))
        )
        (setq i (1+ i))
      )
      (vla-EndUndoMark doc)
      (setq undo-open nil)
      (princ (strcat "\nSSUO ?????????? " (itoa (sslength ss)) " ??????"))
    )
    (princ "\n???????????????2???")
  )
  (princ)
)

(defun c:SJ (/ *error* oldOsMode ss i ent ed p1 p2 top sp ep)
  (setq oldOsMode (getvar "OSMODE"))
  (defun *error* (msg)
    (setvar "OSMODE" oldOsMode)
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setvar "OSMODE" 0)
  (princ "\n=== SJ ????? ===")
  (if (setq ss (ssget '((0 . "LINE"))))
    (progn
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i)
              ed  (entget ent)
              p1  (cdr (assoc 10 ed))
              p2  (cdr (assoc 11 ed)))
        (setq top (if (> (cadr p1) (cadr p2)) p1 p2))
        (setq sp (list (+ (car top) 1.0) (cadr top) (caddr top))
              ep (list (car top) (- (cadr top) 1.0) (caddr top)))
        (command "._LINE" "_non" sp "_non" ep "")
        (setq i (1+ i))
      )
      (princ (strcat "\n????? " (itoa (sslength ss)) " ????????????????"))
    )
    (princ "\n??????????????????????? SJ")
  )
  (setvar "OSMODE" oldOsMode)
  (princ)
)

(defun c:XJ (/ *error* oldOsMode ss i ent ed p1 p2 bot sp ep)
  (setq oldOsMode (getvar "OSMODE"))
  (defun *error* (msg)
    (setvar "OSMODE" oldOsMode)
    (if (and msg
             (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*,*QUIT*")))
      (princ (strcat "\n????: " msg))
    )
    (princ)
  )
  (setvar "OSMODE" 0)
  (princ "\n=== XJ ????? ===")
  (if (setq ss (ssget '((0 . "LINE"))))
    (progn
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i)
              ed  (entget ent)
              p1  (cdr (assoc 10 ed))
              p2  (cdr (assoc 11 ed)))
        (setq bot (if (< (cadr p1) (cadr p2)) p1 p2))
        (setq sp (list (+ (car bot) 1.0) (cadr bot) (caddr bot))
              ep (list (car bot) (+ (cadr bot) 1.0) (caddr bot)))
        (command "._LINE" "_non" sp "_non" ep "")
        (setq i (1+ i))
      )
      (princ (strcat "\n????? " (itoa (sslength ss)) " ????????????????"))
    )
    (princ "\n??????????????????????? XJ")
  )
  (setvar "OSMODE" oldOsMode)
  (princ)
)

(defun c:LONG (/ ss total-length index ename obj)
  (prompt "\n???????????????????: ")
  (setq ss (ssget '((0 . "LINE,POLYLINE,LWPOLYLINE"))))
  (if ss
    (progn
      (setq total-length 0.0 index 0)
      (repeat (sslength ss)
        (setq ename (ssname ss index))
        (setq obj (vlax-ename->vla-object ename))
        (setq total-length (+ total-length (vla-get-length obj)))
        (setq index (1+ index))
      )
      (prompt (strcat "\n??????????????: " (rtos total-length)))
    )
    (prompt "\n???????百汎???")
  )
  (princ)
)

(princ "\n[YS-Tools] line-tools.lsp loaded.")
(princ)
