;;; ====================================================================
;;; YS-Tools - ??????????
;;; ????: CONT TXT T YSDL HEI QSTXT HE QW WI GTX GTY
;;; ====================================================================

;;; --- YSDL ?????????CSV ---
(defun aa:ysdl-get-raw-text (edata / etype raw pair)
  (setq etype (cdr (assoc 0 edata))
        raw   "")
  (cond
    ((= etype "MTEXT")
     (foreach pair edata
       (if (or (= (car pair) 3) (= (car pair) 1))
         (setq raw (strcat raw (cdr pair)))
       )
     )
    )
    (T
     (setq raw (cdr (assoc 1 edata)))
    )
  )
  (if raw raw "")
)

(defun aa:ysdl-strip-mtext-format (str / idx len out ch next semi stack)
  (setq str (if str str "")
        idx 1
        len (strlen str)
        out "")
  (while (<= idx len)
    (setq ch (substr str idx 1))
    (cond
      ((or (= ch "{") (= ch "}"))
       (setq idx (1+ idx)))
      ((/= ch "\\")
       (setq out (strcat out ch)
             idx (1+ idx)))
      ((= idx len)
       (setq idx (1+ idx)))
      (T
       (setq next (substr str (1+ idx) 1))
       (cond
         ((or (= next "\\") (= next "{") (= next "}"))
          (setq out (strcat out next)
                idx (+ idx 2)))
         ((or (= next "P") (= next "p") (= next "~"))
          (setq out (strcat out " ")
                idx (+ idx 2)))
         ((or (= next "L") (= next "l")
              (= next "O") (= next "o")
              (= next "K") (= next "k")
              (= next "X"))
          (setq idx (+ idx 2)))
         ((= next "S")
          (setq semi (vl-string-search ";" str (+ idx 1)))
          (if semi
            (progn
              (setq stack (substr str (+ idx 2) (- semi idx 1)))
              (setq stack (aa:str-replace-all "#" "/" stack))
              (setq stack (aa:str-replace-all "^" "/" stack))
              (setq out (strcat out stack)
                    idx (+ semi 2)))
            (setq idx (+ idx 2))
          )
         )
         ((or (= next "A") (= next "C") (= next "c")
              (= next "F") (= next "f")
              (= next "H") (= next "Q")
              (= next "T") (= next "W"))
          (setq semi (vl-string-search ";" str (+ idx 1)))
          (if semi
            (setq idx (+ semi 2))
            (setq idx (+ idx 2))
          )
         )
         (T
          (setq out (strcat out next)
                idx (+ idx 2)))
       )
      )
    )
  )
  out
)

(defun aa:ysdl-get-plain-text (edata / raw)
  (setq raw (aa:ysdl-get-raw-text edata))
  (if (= (cdr (assoc 0 edata)) "MTEXT")
    (setq raw (aa:ysdl-strip-mtext-format raw))
  )
  raw
)

(defun aa:ysdl-needs-text-formula (str / first)
  (and str
       (> (strlen str) 0)
       (setq first (substr str 1 1))
       (or (= first "=") (= first "+") (= first "-") (= first "@")))
)

(defun aa:ysdl-build-csv-field (cell / field)
  (setq field (if cell cell ""))
  (if (aa:ysdl-needs-text-formula field)
    (setq field (strcat (chr 9) field))
  )
  (setq field (aa:str-replace-all "\"" "\"\"" field))
  (strcat "\"" field "\"")
)

(defun c:YSDL (/ *error* ss i ent edata text-data-list sorted-data
               csv-path f fuzz userprofile file-mode action-msg
               ename targetColor text-string ins-point all-rows current-row
               last-y item current-y line-str cell cell-safe)
  (vl-load-com)
  (defun *error* (msg)
    (if (and (boundp 'f) (= (type f) 'FILE))
      (close f)
    )
    (if (not (wcmatch (strcase msg) "*CANCEL*,*QUIT*"))
      (princ (strcat "\n????????: " msg))
    )
    (princ)
  )
  (setq fuzz *YSDL_RowFuzz*)
  (princ "\n???????????????????????????: ")
  (setq ss (ssget '((0 . "TEXT,MTEXT"))))
  (if ss
    (progn
      (setq text-data-list '()
            i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i))
        (setq edata (entget ent))
        (setq text-string (aa:ysdl-get-plain-text edata))
        (setq ins-point (cdr (assoc 10 edata)))
        (setq text-data-list (cons (list text-string ins-point) text-data-list))
        (setq i (1+ i))
      )
      (setq sorted-data
             (vl-sort text-data-list
                      '(lambda (item1 item2)
                         (setq y1 (cadr (cadr item1)))
                         (setq y2 (cadr (cadr item2)))
                         (if (> y1 (+ y2 fuzz))
                           T
                           (if (< y1 (- y2 fuzz))
                             nil
                             (< (car (cadr item1)) (car (cadr item2)))
                           )
                         )
                       )
             )
      )
      (setq all-rows '())
      (if sorted-data
        (progn
          (setq current-row (list (car (car sorted-data))))
          (setq last-y (cadr (cadr (car sorted-data))))
          (foreach item (cdr sorted-data)
            (setq current-y (cadr (cadr item)))
            (if (<= (abs (- current-y last-y)) fuzz)
              (setq current-row (append current-row (list (car item))))
              (progn
                (setq all-rows (append all-rows (list current-row)))
                (setq current-row (list (car item)))
              )
            )
            (setq last-y current-y)
          )
          (setq all-rows (append all-rows (list current-row)))
        )
      )
      (setq userprofile (getenv "USERPROFILE"))
      (if (and userprofile (/= userprofile ""))
        (progn
          (setq csv-path (strcat userprofile "\\Desktop\\" *YSDL_CsvFileName*))
          (if (findfile csv-path)
            (progn (setq file-mode "a") (setq action-msg "???????????????????:\n"))
            (progn (setq file-mode "w") (setq action-msg "?????????????????????:\n"))
          )
          (setq f (open csv-path file-mode))
          (foreach row all-rows
            (setq line-str "")
            (foreach cell row
                (setq cell-safe (aa:ysdl-build-csv-field cell))
                (setq line-str (strcat line-str cell-safe ","))
            )
            (setq line-str (substr line-str 1 (1- (strlen line-str))))
            (write-line line-str f)
          )
          (close f)
          (setq targetColor *YSDL_TextColor*)
          (setq i 0)
          (repeat (sslength ss)
            (setq ename (ssname ss i))
            (vla-put-Color (vlax-ename->vla-object ename) targetColor)
            (setq i (1+ i))
          )
          (alert (strcat action-msg csv-path "\n\n??????快?????????????"))
        )
        (alert "????: ?????????????﹞??!")
      )
    )
    (princ "\n汛????百????????")
  )
  (princ)
)

;;; --- CONT ??????? ---
(defun C:CONT ( / ss i en edata ent-list sorted-list ref-pt target-x current-y new-pt etype orig-z top-en top-edata pt)
  (command "_.UNDO" "_Begin")
  (setq ss (ssget "_P" '((0 . "TEXT,MTEXT"))))
  (if (not ss)
    (progn
      (princ "\n汛?????孝??????????????快?????: ")
      (setq ss (ssget '((0 . "TEXT,MTEXT"))))
    )
  )
  (if ss
    (progn
      (if (not (tblsearch "STYLE" *CONT_TextStyle*))
        (alert (strcat "????\n\n??????志????????\"" *CONT_TextStyle* "\"???????????\n???????????????????????妊?"))
        (progn
          (setq i 0 ent-list '())
          (repeat (sslength ss)
            (setq en (ssname ss i))
            (setq edata (entget en))
            (setq pt (cdr (assoc 10 edata)))
            (setq ent-list (cons (list (cadr pt) en) ent-list))
            (setq i (1+ i))
          )
          (setq sorted-list (vl-sort ent-list '(lambda (a b) (> (car a) (car b)))))
          (setq top-en (cadr (car sorted-list)))
          (setq top-edata (entget top-en))
          (setq ref-pt (cdr (assoc 10 top-edata)))
          (setq target-x (car ref-pt))
          (setq current-y (cadr ref-pt))
          (foreach item sorted-list
            (setq en (cadr item))
            (setq edata (entget en))
            (setq etype (cdr (assoc 0 edata)))
            (setq orig-z (caddr (cdr (assoc 10 edata))))
            (setq new-pt (list target-x current-y orig-z))
            (setq edata (subst (cons 7 *CONT_TextStyle*) (assoc 7 edata) edata))
            (setq edata (subst (cons 40 *CONT_TextHeight*) (assoc 40 edata) edata))
            (setq edata (subst (cons 10 new-pt) (assoc 10 edata) edata))
            (if (= etype "TEXT")
              (progn
                (setq edata (subst (cons 41 *CONT_TextWidthFactor*) (assoc 41 edata) edata))
                (setq edata (subst (cons 72 0) (assoc 72 edata) edata))
                (setq edata (subst (cons 73 0) (assoc 73 edata) edata))
              )
              (setq edata (subst (cons 71 7) (assoc 71 edata) edata))
            )
            (entmod edata)
            (setq current-y (- current-y *CONT_LineSpacing*))
          )
          (princ (strcat "\n?????????? " (itoa (length sorted-list)) " ?????????"))
        )
      )
    )
    (princ "\n汛????百????????")
  )
  (command "_.UNDO" "_End")
  (princ)
)

;;; --- TXT/T ???????? ---
(defun txt:set-dxf (code value data / item)
  (if (setq item (assoc code data))
    (subst (cons code value) item data)
    (append data (list (cons code value)))
  )
)

(defun txt:collect-new-ents (before after / result cur)
  (cond
    ((null after) nil)
    ((null before) (list after))
    ((eq before after) nil)
    (t
      (setq cur (entnext before))
      (while cur
        (setq result (cons cur result))
        (if (eq cur after)
          (setq cur nil)
          (setq cur (entnext cur))
        )
      )
      (reverse result)
    )
  )
)

(defun txt:modify-text (ename / edata)
  (if (and ename (= "TEXT" (cdr (assoc 0 (setq edata (entget ename))))))
    (progn
      (setq edata (txt:set-dxf 7 "HZ" edata))
      (setq edata (txt:set-dxf 40 3.0 edata))
      (setq edata (txt:set-dxf 41 0.7 edata))
      (entmod edata)
      (entupd ename)
    )
  )
)

(defun txt:run (/ *error* oldcmdecho sel i ename etype txtss mtlist before after)
  (defun *error* (msg)
    (if oldcmdecho
      (setvar "CMDECHO" oldcmdecho)
    )
    (if (and msg (/= msg "Function cancelled") (/= msg "quit / exit abort"))
      (princ (strcat "\nError: " msg))
    )
    (princ)
  )
  (if (null (tblsearch "STYLE" "HZ"))
    (princ "\nText style HZ was not found.")
    (progn
      (setq sel (ssget))
      (if sel
        (progn
          (setq oldcmdecho (getvar "CMDECHO"))
          (setvar "CMDECHO" 0)
          (setq txtss (ssadd)
                mtlist '()
                i 0)
          (while (< i (sslength sel))
            (setq ename (ssname sel i)
                  etype (cdr (assoc 0 (entget ename))))
            (cond
              ((= etype "TEXT")
               (ssadd ename txtss))
              ((= etype "MTEXT")
               (setq mtlist (cons ename mtlist)))
            )
            (setq i (1+ i))
          )
          (foreach ename (reverse mtlist)
            (setq before (entlast))
            (command "_.explode" ename)
            (setq after (entlast))
            (foreach newent (txt:collect-new-ents before after)
              (if (= "TEXT" (cdr (assoc 0 (entget newent))))
                (ssadd newent txtss)
              )
            )
          )
          (setq i 0)
          (while (< i (sslength txtss))
            (txt:modify-text (ssname txtss i))
            (setq i (1+ i))
          )
          (sssetfirst nil txtss)
          (setvar "CMDECHO" oldcmdecho)
          (princ (strcat "\nProcessed text count: " (itoa (sslength txtss))))
        )
        (princ "\n???????百汎???")
      )
    )
  )
  (princ)
)

(defun c:TXT () (txt:run))
(defun c:T () (txt:run))

;;; --- HEI ??????? ---
(defun c:HEI (/ a ss ent ent_data text_type insertion_point x y text_content
              text_list sorted_text_list base_x max_y current_y count modified_data)
  (vl-load-com)
  (setq a (getdist "\n???????????? <5>: "))
  (if (not a) (setq a 5))
  (princ "\n???????快????????: ")
  (setq ss (ssget '((0 . "TEXT,MTEXT"))))
  (if ss
    (progn
      (setq text_list '() count 0)
      (repeat (sslength ss)
        (setq ent (ssname ss count) ent_data (entget ent) text_type (cdr (assoc 0 ent_data)) modified_data ent_data)
        (cond
          ((= text_type "TEXT")
            (if (assoc 72 modified_data)
                (setq modified_data (subst (cons 72 0) (assoc 72 modified_data) modified_data))
                (setq modified_data (append modified_data (list (cons 72 0))))
            )
            (if (assoc 73 modified_data)
                (setq modified_data (subst (cons 73 0) (assoc 73 modified_data) modified_data))
                (setq modified_data (append modified_data (list (cons 73 0))))
            )
            (if (assoc 11 modified_data) (setq modified_data (vl-remove (assoc 11 modified_data) modified_data)))
          )
          ((= text_type "MTEXT")
            (if (assoc 71 modified_data)
                (setq modified_data (subst (cons 71 1) (assoc 71 modified_data) modified_data))
                (setq modified_data (append modified_data (list (cons 71 1))))
            )
          )
        )
        (entmod modified_data)
        (setq ent_data (entget ent)
              insertion_point (cdr (assoc 10 ent_data))
              x (car insertion_point)
              y (cadr insertion_point)
              text_content (cdr (assoc 1 ent_data))
        )
        (setq text_list (cons (list y x text_content ent) text_list))
        (setq count (1+ count))
      )
      (setq sorted_text_list (vl-sort text_list '(lambda (a b) (> (car a) (car b)))))
      (setq base_x (apply 'min (mapcar 'cadr sorted_text_list))
            max_y (apply 'max (mapcar 'car sorted_text_list)))
      (setq current_y max_y count 0)
      (foreach text_info sorted_text_list
        (setq ent (car (last text_info)) ent_data (entget ent))
        (setq new_insertion_point (list base_x current_y (caddr (cdr (assoc 10 ent_data))))
              ent_data (subst (cons 10 new_insertion_point) (assoc 10 ent_data) ent_data))
        (entmod ent_data)
        (setq current_y (- current_y a))
        (setq count (1+ count))
      )
      (princ (strcat "\n????????? " (itoa count) " ?????????????????????"))
    )
    (princ "\n[HEI] ?????")
  )
  (princ)
)

;;; --- QSTXT ??????????? ---
(defun c:qstxt (/ ss i ent txt)
  (setq ss (ssget))
  (if ss
    (progn
      (setq txt (ssadd))
      (setq i 0)
      (while (< i (sslength ss))
        (setq ent (ssname ss i))
        (if (wcmatch (cdr (assoc 0 (entget ent))) "*TEXT")
          (ssadd ent txt)
        )
        (setq i (1+ i))
      )
      (if (> (sslength txt) 0)
        (progn
          (sssetfirst nil txt)
          (princ (strcat "\n????? " (itoa (sslength txt)) " ?????????"))
        )
        (princ "\n??????????????????")
      )
    )
    (princ "\n???????百汎???")
  )
  (princ)
)

;;; --- HE ???/???????? ---
(defun c:HE (/ ss lst i ent ent-data pt txt ht sorted-lst master-ent master-data new-str)
  (vl-load-com)
  (princ "\n???????????????(????????㏒??????????????):")
  (if (setq ss (ssget '((0 . "TEXT,MTEXT"))))
    (progn
      (setq lst '())
      (setq i 0)
      (repeat (sslength ss)
        (setq ent (ssname ss i))
        (setq ent-data (entget ent))
        (setq pt (cdr (assoc 10 ent-data)))
        (setq txt (cdr (assoc 1 ent-data)))
        (setq ht (cdr (assoc 40 ent-data)))
        (setq lst (cons (list ent pt txt ht) lst))
        (setq i (1+ i))
      )
      (setq sorted-lst
        (vl-sort lst
          (function (lambda (e1 e2 / p1 p2 h y1 y2 x1 x2)
            (setq p1 (cadr e1))
            (setq p2 (cadr e2))
            (setq h (cadddr e1))
            (setq y1 (cadr p1))
            (setq y2 (cadr p2))
            (setq x1 (car p1))
            (setq x2 (car p2))
            (if (> (abs (- y1 y2)) (* h 0.5))
              (> y1 y2)
              (< x1 x2)
            )
          ))
        )
      )
      (setq master-ent (car (car sorted-lst)))
      (setq new-str "")
      (foreach item sorted-lst
        (setq new-str (strcat new-str (caddr item)))
      )
      (setq master-data (entget master-ent))
      (setq master-data (subst (cons 1 new-str) (assoc 1 master-data) master-data))
      (entmod master-data)
      (entupd master-ent)
      (foreach item (cdr sorted-lst)
        (entdel (car item))
      )
      (princ (strcat "\n?????? " (itoa (length sorted-lst)) " ????????????: " new-str))
    )
    (princ "\n汛????百????????")
  )
  (princ)
)

;;; --- QW ??????????? ---
(defun c:QW (/ a ss i ent data)
  (setq a (getdist "\n???????米???????: "))
  (if (and a (> a 0))
    (progn
      (princ "\n???????????????????...")
      (setq ss (ssget '((0 . "TEXT,MTEXT"))))
      (if ss
        (progn
          (setq i 0)
          (repeat (sslength ss)
            (setq ent (ssname ss i))
            (setq data (entget ent))
            (setq data (subst (cons 40 a) (assoc 40 data) data))
            (entmod data)
            (setq i (1+ i))
          )
          (princ (strcat "\n???????????? " (itoa i) " ?????????????: " (rtos a)))
        )
        (princ "\n汛????百????????")
      )
    )
    (princ "\n????????完?????????")
  )
  (princ)
)

;;; --- WI ?????????????? ---
(defun c:wi (/ a ss i ename elist old_width)
  (setq a (getreal "\n???????米???????????? (?? 0.8 ?? 1.0): "))
  (if (and a (> a 0))
    (progn
      (princ "\n?????????????????: ")
      (setq ss (ssget '((0 . "TEXT,MTEXT"))))
      (if ss
        (progn
          (setq i 0)
          (repeat (sslength ss)
            (setq ename (ssname ss i))
            (setq elist (entget ename))
            (if (assoc 41 elist)
              (setq elist (subst (cons 41 a) (assoc 41 elist) elist))
              (setq elist (append elist (list (cons 41 a))))
            )
            (entmod elist)
            (setq i (1+ i))
          )
          (princ (strcat "\n???????? " (itoa (sslength ss)) " ??????????????"))
        )
        (princ "\n汛????百???完?????????")
      )
    )
    (princ "\n??完?????????????????????0???????")
  )
  (princ)
)

;;; --- GTX ??????? ---
(defun aa:gtx-find-last-char (char str / len pos)
  (setq len (strlen str)
        pos nil)
  (while (and (> len 0) (not pos))
    (if (= (substr str len 1) char)
      (setq pos len)
      (setq len (1- len))
    )
  )
  pos
)

(defun aa:gtx-parse-suffix (suffix / i char num-str alpha-str)
  (setq i 1
        num-str ""
        alpha-str "")
  (while (<= i (strlen suffix))
    (setq char (substr suffix i 1))
    (if (wcmatch char "#")
      (setq num-str (strcat num-str char))
      (setq alpha-str (strcat alpha-str char))
    )
    (setq i (1+ i))
  )
  (list (atoi num-str) alpha-str)
)

(defun aa:gtx-create-text-entity (pt content h sty)
  (entmake
    (list
      '(0 . "TEXT")
      (cons 10 pt)
      (cons 40 h)
      (cons 1 content)
      (cons 7 sty)
      '(41 . 0.7)
      '(62 . 7)))
)

(defun aa:gtx-first-text-from-ss (ss / i en)
  (setq i 0
        en nil)
  (while (and ss (< i (sslength ss)) (not en))
    (if (eq "TEXT" (cdr (assoc 0 (entget (ssname ss i)))))
      (setq en (ssname ss i))
    )
    (setq i (1+ i))
  )
  en
)

(defun aa:gtx-select-prefix-text (/ prefix-ss prefix-ent)
  (setq prefix-ent nil)
  (while (not prefix-ent)
    (sssetfirst nil nil)
    (prompt "\n[GTX] ???????????????????(?????): ")
    (setq prefix-ss (ssget '((0 . "TEXT"))))
    (setq prefix-ent (aa:gtx-first-text-from-ss prefix-ss))
    (if (not prefix-ent)
      (prompt "\n[GTX] 汛???????????????TEXT????Esc?????")
    )
  )
  prefix-ent
)

(defun c:GTX (/ *error* ss i ent ent-data text-data text-string insertion-point
               lines current-item current-y found line categorized-groups
               left-text temp-text last-hyphen-pos category group-texts found-category
               pt start-x current-x col-width line-height text-height text-style
               category-group groups-in-category sorted-groups group text-item
               split-groups current-group last-item-x current-item-x
               prefix-text-ent prefix-text-str)
  (vl-load-com)
  (setq text-style (if (tblsearch "STYLE" "HZ") "HZ" (getvar "TEXTSTYLE")))
  (defun *error* (msg)
    (if (not (member msg '("Function cancelled" "quit / exit abort")))
      (princ (strcat "\n[GTX] Error: " msg))
    )
    (sssetfirst nil nil)
    (princ)
  )
  (setq ss (ssget "_I" '((0 . "TEXT"))))
  (if (not ss)
    (progn
      (prompt "\n[GTX] ?????????????: ")
      (setq ss (ssget '((0 . "TEXT"))))
    )
  )
  (if ss
    (progn
      (setq prefix-text-ent (aa:gtx-select-prefix-text))
      (setq prefix-text-str (cdr (assoc 1 (entget prefix-text-ent))))
      (if prefix-text-str
        (progn
          (setq text-data '()
                i         0)
          (repeat (sslength ss)
            (setq ent             (ssname ss i)
                  ent-data        (entget ent)
                  text-string     (cdr (assoc 1 ent-data))
                  insertion-point (cdr (assoc 10 ent-data))
                  text-data       (cons (list text-string insertion-point) text-data)
                  i               (1+ i))
          )
          (setq lines '())
          (foreach current-item text-data
            (setq current-y (cadr (cadr current-item))
                  found     nil)
            (setq lines
              (mapcar
                '(lambda (line)
                   (if (and (not found)
                            (< (abs (- current-y (cadr (cadr (car line))))) 1.0))
                     (progn
                       (setq found T)
                       (cons current-item line))
                     line))
                lines))
            (if (not found)
              (setq lines (cons (list current-item) lines)))
          )
          (setq lines
            (mapcar
              '(lambda (line)
                 (vl-sort line '(lambda (a b) (< (car (cadr a)) (car (cadr b))))))
              lines))
          (setq split-groups '())
          (foreach line lines
            (if line
              (progn
                (setq current-group (list (car line))
                      last-item-x   (car (cadr (car line))))
                (foreach item (cdr line)
                  (setq current-item-x (car (cadr item)))
                  (if (> (- current-item-x last-item-x) 200.0)
                    (progn
                      (setq split-groups (cons current-group split-groups))
                      (setq current-group (list item)))
                    (setq current-group (append current-group (list item)))
                  )
                  (setq last-item-x current-item-x)
                )
                (setq split-groups (cons current-group split-groups))
              )
            )
          )
          (setq lines (reverse split-groups))
          (setq categorized-groups '())
          (foreach line lines
            (if (>= (length line) 1)
              (progn
                (setq left-text (caar line)
                      temp-text left-text)
                (if (wcmatch temp-text "??*")
                  (setq temp-text (vl-string-subst "" "??" temp-text))
                )
                (setq last-hyphen-pos (aa:gtx-find-last-char "-" temp-text))
                (if last-hyphen-pos
                  (setq category (substr temp-text 1 last-hyphen-pos))
                  (setq category temp-text)
                )
                (setq group-texts    (mapcar 'car line)
                      found-category (assoc category categorized-groups))
                (if found-category
                  (setq categorized-groups
                    (subst
                      (list category (cons group-texts (cadr found-category)))
                      found-category
                      categorized-groups))
                  (setq categorized-groups
                    (cons (list category (list group-texts)) categorized-groups))
                )
              )
            )
          )
          (setq pt (getpoint "\n[GTX] ??????????????: "))
          (if pt
            (progn
              (setq text-height 3.0
                    start-x     (car pt)
                    current-y   (cadr pt)
                    col-width   50.0
                    line-height (* 1.4 text-height))
              (setq categorized-groups
                (vl-sort categorized-groups '(lambda (a b) (< (car a) (car b)))))
              (foreach category-group categorized-groups
                (setq groups-in-category (cadr category-group))
                (setq sorted-groups
                  (vl-sort
                    groups-in-category
                    '(lambda (itemA itemB / keyA keyB posA posB suffixA suffixB parsedA parsedB numA alphaA numB alphaB)
                       (setq keyA (car itemA)
                             keyB (car itemB)
                             posA (aa:gtx-find-last-char "-" keyA)
                             posB (aa:gtx-find-last-char "-" keyB))
                       (if (and posA posB)
                         (progn
                           (setq suffixA (substr keyA (1+ posA))
                                 suffixB (substr keyB (1+ posB))
                                 parsedA (aa:gtx-parse-suffix suffixA)
                                 parsedB (aa:gtx-parse-suffix suffixB)
                                 numA    (car parsedA)
                                 alphaA  (cadr parsedA)
                                 numB    (car parsedB)
                                 alphaB  (cadr parsedB))
                           (if (= numA numB)
                             (< alphaA alphaB)
                             (< numA numB)))
                         (< keyA keyB))))
                )
                (foreach group sorted-groups
                  (setq current-x start-x)
                  (aa:gtx-create-text-entity (list current-x current-y 0.0) prefix-text-str text-height text-style)
                  (setq current-x (+ current-x col-width))
                  (foreach text-item group
                    (aa:gtx-create-text-entity (list current-x current-y 0.0) text-item text-height text-style)
                    (setq current-x (+ current-x col-width))
                  )
                  (setq current-y (- current-y line-height))
                )
                (setq current-y (- current-y (* 0.5 line-height)))
              )
              (princ "\n[GTX] ?????????阱?")
            )
            (princ "\n[GTX] ???????????")
          )
        )
        (princ "\n[GTX] 汛?????完?????????")
      )
    )
    (princ "\n[GTX] 汛????????")
  )
  (sssetfirst nil nil)
  (princ)
)

;;; --- GTY ???????????? ---
(defun aa:gty-pad-left (txt size / result)
  (setq result txt)
  (while (< (strlen result) size)
    (setq result (strcat "0" result))
  )
  result
)

(defun aa:gty-normalize-key (txt / src i char num-buf result)
  (setq src     (strcase (vl-string-trim " " (if txt txt "")))
        i       1
        num-buf ""
        result  "")
  (while (<= i (strlen src))
    (setq char (substr src i 1))
    (if (wcmatch char "#")
      (setq num-buf (strcat num-buf char))
      (progn
        (if (> (strlen num-buf) 0)
          (progn
            (setq result  (strcat result (aa:gty-pad-left num-buf 8))
                  num-buf ""))
        )
        (setq result (strcat result char))
      )
    )
    (setq i (1+ i))
  )
  (if (> (strlen num-buf) 0)
    (setq result (strcat result (aa:gty-pad-left num-buf 8)))
  )
  result
)

(defun aa:gty-get-item-ename (item) (nth 0 item))
(defun aa:gty-get-item-text  (item) (nth 1 item))
(defun aa:gty-get-item-pt    (item) (nth 2 item))
(defun aa:gty-get-item-x     (item) (car (aa:gty-get-item-pt item)))
(defun aa:gty-get-item-y     (item) (cadr (aa:gty-get-item-pt item)))
(defun aa:gty-get-item-z     (item / pt)
  (setq pt (aa:gty-get-item-pt item))
  (if (caddr pt) (caddr pt) 0.0)
)
(defun aa:gty-get-item-width (item) (nth 3 item))
(defun aa:gty-get-item-height (item) (nth 4 item))

(defun aa:gty-build-sort-key (row idx / key)
  (if (>= (length row) 4)
    (setq key (aa:gty-normalize-key (aa:gty-get-item-text (nth 1 row))))
    (setq key "")
  )
  (strcat
    (if (> (strlen key) 0) "0|" "1|")
    key
    "|"
    (aa:gty-pad-left (itoa idx) 6))
)

(defun aa:gty-get-text-width (edata / box p1 p2 h txt)
  (setq h   (cond ((cdr (assoc 40 edata))) (3.0))
        txt (cdr (assoc 1 edata))
        box (textbox edata))
  (if (and box (= (length box) 2))
    (progn
      (setq p1 (car box)
            p2 (cadr box))
      (max (- (car p2) (car p1)) h))
    (max (* (strlen txt) h 0.7) h))
)

(defun aa:gty-update-nth (idx val lst / n result)
  (setq n 0
        result '())
  (foreach itm lst
    (setq result (cons (if (= n idx) val itm) result)
          n      (1+ n))
  )
  (reverse result)
)

(defun aa:gty-move-entity (ename from-pt to-pt / obj)
  (setq obj (vlax-ename->vla-object ename))
  (vla-move obj (vlax-3d-point from-pt) (vlax-3d-point to-pt))
)

(defun c:GTY (/ *error* ss i ent ent-data text-string insertion-point text-height text-width
               text-data total-height avg-height row-tol split-gap col-gap line-height
               rows current-item current-y found split-rows current-row last-item-x current-item-x
               anchor-x anchor-y col-widths col-index row row-index sort-keys row-map token sorted-rows
               doc undo-started)
  (vl-load-com)
  (setq doc          (vla-get-ActiveDocument (vlax-get-acad-object))
        undo-started nil)
  (defun *error* (msg)
    (if undo-started
      (vla-EndUndoMark doc)
    )
    (if (not (member msg '("Function cancelled" "quit / exit abort")))
      (princ (strcat "\n[GTY] Error: " msg))
    )
    (sssetfirst nil nil)
    (princ)
  )
  (setq ss (ssget "_I" '((0 . "TEXT"))))
  (if (not ss)
    (progn
      (prompt "\n[GTY] ??????????????????: ")
      (setq ss (ssget '((0 . "TEXT"))))
    )
  )
  (if ss
    (progn
      (vla-StartUndoMark doc)
      (setq undo-started T
            text-data     '()
            total-height  0.0
            i             0)
      (repeat (sslength ss)
        (setq ent             (ssname ss i)
              ent-data        (entget ent)
              text-string     (cdr (assoc 1 ent-data))
              insertion-point (cdr (assoc 10 ent-data))
              text-height     (cond ((cdr (assoc 40 ent-data))) (3.0))
              text-width      (aa:gty-get-text-width ent-data)
              text-data       (cons (list ent text-string insertion-point text-width text-height) text-data)
              total-height    (+ total-height text-height)
              i               (1+ i))
      )
      (setq text-data (reverse text-data))
      (setq avg-height  (/ total-height (max 1 (length text-data)))
            row-tol     (max 1.0 (* avg-height 0.6))
            split-gap   200.0
            col-gap     (max 10.0 (* avg-height 2.0))
            line-height (max (* avg-height 1.6) (+ avg-height 1.0)))
      (setq rows '())
      (foreach current-item text-data
        (setq current-y (aa:gty-get-item-y current-item)
              found     nil)
        (setq rows
          (mapcar
            '(lambda (line)
               (if (and (not found)
                        (<= (abs (- current-y (aa:gty-get-item-y (car line)))) row-tol))
                 (progn
                   (setq found T)
                   (cons current-item line))
                 line))
            rows))
        (if (not found)
          (setq rows (cons (list current-item) rows))
        )
      )
      (setq rows
        (mapcar
          '(lambda (line)
             (vl-sort line '(lambda (a b) (< (aa:gty-get-item-x a) (aa:gty-get-item-x b)))))
          rows))
      (setq split-rows '())
      (foreach row rows
        (if row
          (progn
            (setq current-row (list (car row))
                  last-item-x (aa:gty-get-item-x (car row)))
            (foreach current-item (cdr row)
              (setq current-item-x (aa:gty-get-item-x current-item))
              (if (> (- current-item-x last-item-x) split-gap)
                (progn
                  (setq split-rows (cons current-row split-rows))
                  (setq current-row (list current-item)))
                (setq current-row (append current-row (list current-item)))
              )
              (setq last-item-x current-item-x)
            )
            (setq split-rows (cons current-row split-rows))
          )
        )
      )
      (setq rows (reverse split-rows))
      (setq rows
        (vl-sort
          rows
          '(lambda (a b / ay by ax bx)
             (setq ay (aa:gty-get-item-y (car a))
                   by (aa:gty-get-item-y (car b))
                   ax (aa:gty-get-item-x (car a))
                   bx (aa:gty-get-item-x (car b)))
             (if (> (abs (- ay by)) row-tol)
               (> ay by)
               (< ax bx)))))
      (setq anchor-x (aa:gty-get-item-x (car text-data))
            anchor-y (aa:gty-get-item-y (car text-data)))
      (foreach current-item text-data
        (if (< (aa:gty-get-item-x current-item) anchor-x)
          (setq anchor-x (aa:gty-get-item-x current-item))
        )
        (if (> (aa:gty-get-item-y current-item) anchor-y)
          (setq anchor-y (aa:gty-get-item-y current-item))
        )
      )
      (setq col-widths '())
      (foreach row rows
        (setq col-index 0)
        (foreach current-item row
          (if (>= col-index (length col-widths))
            (setq col-widths
              (append col-widths (list (max (aa:gty-get-item-width current-item) col-gap))))
            (if (> (aa:gty-get-item-width current-item) (nth col-index col-widths))
              (setq col-widths
                (aa:gty-update-nth col-index (aa:gty-get-item-width current-item) col-widths))
            )
          )
          (setq col-index (1+ col-index))
        )
      )
      (setq sort-keys '()
            row-map   '()
            row-index 0)
      (foreach row rows
        (setq token     (aa:gty-build-sort-key row row-index)
              sort-keys (cons token sort-keys)
              row-map   (cons (cons token row) row-map)
              row-index (1+ row-index))
      )
      (setq sorted-rows
        (mapcar
          '(lambda (key) (cdr (assoc key row-map)))
          (vl-sort sort-keys '(lambda (a b) (< a b)))))
      (setq row-index 0)
      (foreach row sorted-rows
        (setq current-item-x anchor-x
              col-index      0)
        (foreach current-item row
          (aa:gty-move-entity
            (aa:gty-get-item-ename current-item)
            (aa:gty-get-item-pt current-item)
            (list current-item-x
                  (- anchor-y (* row-index line-height))
                  (aa:gty-get-item-z current-item)))
          (setq current-item-x (+ current-item-x (nth col-index col-widths) col-gap)
                col-index      (1+ col-index))
        )
        (setq row-index (1+ row-index))
      )
      (vla-EndUndoMark doc)
      (setq undo-started nil)
      (princ "\n[GTY] ??????????????阱?")
    )
    (princ "\n[GTY] 汛????????")
  )
  (sssetfirst nil nil)
  (princ)
)

(princ "\n[YS-Tools] text-tools.lsp loaded.")
(princ)
