from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VERSION = "1.5.0"
ENCODING = "gbk"

CORE_SOURCES = [
    ROOT / "YS-Tools" / "config.lsp",
    ROOT / "YS-Tools" / "utils.lsp",
    ROOT / "YS-Tools" / "modules" / "text-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "align-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "color-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "move-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "line-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "draw-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "cable-tools.lsp",
    ROOT / "YS-Tools" / "modules" / "xy-tools.lsp",
]

XY_SOURCES = [
    ROOT / "YS-Tools" / "config.lsp",
    ROOT / "YS-Tools" / "utils.lsp",
    ROOT / "YS-Tools" / "modules" / "xy-tools.lsp",
]

OUTPUTS = {
    ROOT / "AA整合版本.lsp": ("YS-Tools compatibility bundle", CORE_SOURCES),
    ROOT / "小命令" / "芯原XY.lsp": ("YS-Tools XY compatibility bundle", XY_SOURCES),
}


def normalize(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip() + "\n"


def as_bundle_defaults(text: str) -> str:
    lines: list[str] = []
    for line in normalize(text).splitlines():
        code, separator, comment = line.partition(";")
        match = re.match(r"^(\s*)\(setq\s+(\*[^\s()]+\*)\s+", code)
        if match:
            indent, variable = match.groups()
            wrapped = f"{indent}(if (not (boundp '{variable})) {code.strip()})"
            line = wrapped + (f" ;{comment}" if separator else "")
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def render(title: str, sources: list[Path]) -> bytes:
    header = (
        ";;; ====================================================================\n"
        f";;; {title} v{VERSION}\n"
        ";;; AUTO-GENERATED by tools/build_bundle.py - DO NOT EDIT\n"
        ";;; 此文件由模块源码自动生成，禁止手工修改。\n"
        ";;; Encoding: GBK/ANSI, CRLF\n"
        ";;; ====================================================================\n\n"
    )
    sections = [header]
    for source in sources:
        relative = source.relative_to(ROOT).as_posix()
        sections.append(f";;; ----- BEGIN {relative} -----\n")
        source_text = source.read_text(encoding=ENCODING)
        if source.name == "config.lsp":
            source_text = as_bundle_defaults(source_text)
        sections.append(normalize(source_text))
        sections.append(f";;; ----- END {relative} -----\n\n")
    text = "".join(sections).rstrip() + "\n"
    return text.replace("\n", "\r\n").encode(ENCODING)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build CADTools compatibility bundles")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a committed bundle differs from its module sources",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for output, (title, sources) in OUTPUTS.items():
        expected = render(title, sources)
        if args.check:
            if not output.exists() or output.read_bytes() != expected:
                stale.append(output)
        else:
            output.write_bytes(expected)
            print(f"generated: {output.relative_to(ROOT)}")

    if stale:
        for output in stale:
            print(f"stale: {output.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if args.check:
        print("bundles are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
